import paramiko
s = paramiko.SSHClient()
s.set_missing_host_key_policy(paramiko.AutoAddPolicy())
s.connect('217.77.7.228', username='alex', password='123456')
_, o, e = s.exec_command("sudo -S -p '' tail -200 /var/log/nginx/access.log | grep -E 'analyze|classify|preview'")
s.exec_command('123456\n')
o.channel.send('123456\n')
print(o.read().decode())
print(e.read().decode())
s.close()
